### ISSUE TITLE
Bucket Access Denied

### ISSUE THREAD

**Issue by Pierl0** [brantburnett/Couchbase.Extensions#7]
Hello, 
Since I updated the package on friday, I get with exception thrown every time I try to access my bucket in localhost. 
On thursday, everything was fine. 

`10:13:05 ERR] Connection id "0HL6TDGGEGOJ3": An unhandled exception was thrown by the application.
System.TypeLoadException: Access is denied: 'Couchbase.Extensions.DependencyInjection.Internal.NamedBucketProvider'.`

Configuration : 
` "Couchbase": {
    "Servers": [
      "http://localhost:8091/"
    ],
    "Buckets": [
      {
        "Name": "Referential"
      }     
    ]
  }`

**Comment by brantburnett** [comment]
@jeffrymorris

Any thoughts? You're most familiar with the changes in 1.0.1.

**Comment by brantburnett** [comment]
@jeffrymorris 

I have tracked it down.  The problem is that the new 1.0.1 assembly is missing the InternalsVisibleTo attribute for DynamicProxyGenAssembly2, which is required for Castle DynamicProxy.  I can't find a commit that is the culprit, so I'm guessing it's something in the packaging process.

Brant

**Comment by jeffrymorris** [comment]
@brantburnett -

Yeah, that is the issue. I'll push another package this afternoon.

-Jeff

**Comment by brantburnett** [comment]
@Pierl0 

Can you try the new version 1.0.2 released yesterday and see if that fixes it for you?

Thanks,
Brant

**Comment by Pierl0** [comment]
Hello, I just try. 

it works perfectly 👍  
Thanks for the quick fix. 

Pierre-Loic
